FROM ghcr.io/astral-sh/uv:0.7.21 AS uv

FROM apache/airflow:3.2.2-python3.14

USER root

COPY --from=uv /uv /uvx /bin/

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/airflow

COPY airflow-requirements.txt ./

RUN uv pip install --system --no-cache -r airflow-requirements.txt

USER airflow
