FROM ghcr.io/astral-sh/uv:latest AS uv

FROM apache/superset:6.0.0

USER root

COPY --from=uv /uv /uvx /bin/

RUN uv pip install \
    --python /app/.venv/bin/python \
    --no-cache \
    clickhouse-connect \
    psycopg2-binary

COPY --chown=superset:superset \
    superset_config.py \
    /app/pythonpath/superset_config.py

ENV SUPERSET_CONFIG_PATH=/app/pythonpath/superset_config.py

USER superset