import os

SECRET_KEY = os.environ["SUPERSET_SECRET_KEY"]

SQLALCHEMY_DATABASE_URI = os.environ["SUPERSET_DATABASE_URI"]

WTF_CSRF_ENABLED = True

ROW_LIMIT = 5000

SUPERSET_WEBSERVER_PORT = 8088

ENABLE_PROXY_FIX = False
