nyc_taxi:
  target: dev

  outputs:
    dev:
      type: clickhouse

      host: "{{ env_var('CLICKHOUSE_HOST', 'clickhouse') }}"
      port: 8123

      user: "{{ env_var('CLICKHOUSE_USER') }}"
      password: "{{ env_var('CLICKHOUSE_PASSWORD') }}"

      schema: default

      secure: false
      verify: false

      threads: 1
      connect_timeout: 10
      send_receive_timeout: 600

      custom_settings:
        max_threads: 2
        max_insert_threads: 1
        max_memory_usage: 2684354560
        max_bytes_before_external_sort: 536870912
        max_bytes_before_external_group_by: 536870912
        join_algorithm: auto